version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:3.2.0
  env_file:
    - ../.env
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
  depends_on:
    rabbitmq:
      condition: service_healthy

services:

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: airflow
      RABBITMQ_DEFAULT_PASS: airflow
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate &&
               airflow users create
               --username admin
               --password admin
               --firstname Admin
               --lastname User
               --role Admin
               --email admin@example.com"
    restart: on-failure

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  flower:
    <<: *airflow-common
    command: celery flower
    ports:
      - "5555:5555"
    restart: always

